spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/badges
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  application:
    name: "BadgeCollection"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      indent-output: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liHzCV2Xmhgi1rgl
            client-secret: 6eeef036b276f779ad035a5df41d7bfbf90501ca
            scope: read:user,user:email
            redirect-uri: "{baseUrl}/login/oauth2/github"
            client-name: GitHub
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user

